### ISSUE TITLE
Put out signup link for demos

### ISSUE THREAD

**Issue by maxwofford** [hackclub-archive/events#12]
The goal is for 5 demos, which should be around 8 signups at our current rate of attrition.

**Comment by maxwofford** [comment]
@ssun098: Could I get the link for demo sign ups?

**Comment by selynna** [comment]
http://goo.gl/forms/5gzdgR8ynJY8yAzl2

**Comment by maxwofford** [comment]
@ssun098 I've updated the form: https://goo.gl/forms/2d1QT63xAq11AZZy1

**Comment by maxwofford** [comment]
Reassigning to @ssun098 because I'm now at RIT.

**Comment by selynna** [comment]
@MaxWofford could you give me access to the form? Can't find it

**Comment by selynna** [comment]
8 is also a goal and not super actionable, so I changed the wording of the issue. Closing because form is updated across our event pages
