### ISSUE TITLE
Media release forms filled out by attendees

### ISSUE THREAD

**Issue by saescapa** [hackclub-archive/events#20]

**Comment by saescapa** [comment]
@zachlatta Do we have a general media release form or should I create one (just editing some words)? This is the only one I found which was used for Hack Camp:

https://github.com/hackclub/camp/blob/b61574e23b27eeab63578ad4096f660866e8d31b/2016/meta/attendee_packet/media_release.pdf

**Comment by zachlatta** [comment]
The one we used for Hack Camp should work just fine :-)

**Comment by saescapa** [comment]
All right, will just change Hack Camp to Demo Night on the release form. PR at #22

**Comment by selynna** [comment]
Merged #22

**Comment by selynna** [comment]
https://www.hellosign.com/s/5a600ac2 also located here
