### ISSUE TITLE
Find another activity to run

### ISSUE THREAD

**Issue by saescapa** [hackclub-archive/events#21]
List here:
- Cup Stacking (Last resort)
- Spaghettow or Marshguetti

**Comment by saescapa** [comment]
Finalized: Spaghettow or Marshguetti. We are going to need to buy those.

**Comment by maxwofford** [comment]
TIL https://en.wiktionary.org/wiki/spaghetto

**Comment by selynna** [comment]
when your spaghetti is ghetto af

**Comment by maxwofford** [comment]
https://iwantmyname.com/?domain=spaghetto.af

**Comment by selynna** [comment]
$139 WHAT A STEAL
