### ISSUE TITLE
Organize next Hack Night

### ISSUE THREAD

**Issue by selynna** [hackclub-archive/events#34]
This issue the overarching issue containing all the subissues needed to organize the next Hack Night. Once Hack Night has passed, this issue can be closed. 
- [ ] Find 1-2 volunteers from the community to take point on the event. 
- [ ] Figure out a date that works for the most people possible (ideally not conflicting with test dates)
- [ ] Announcements 
  - [ ] Slack post in #announcements a week before Hack Night and day before
  - [ ] Email out to community a week before and the day before

**Comment by paked** [comment]
Closing because this repo has been deprecated.
