### ISSUE TITLE
Find keynote speaker

### ISSUE THREAD

**Issue by selynna** [hackclub-archive/events#9]
This issue is for finding the keynote speaker for our October Demo Night. It can be closed once a speaker confirms that he/she will be coming.

**Comment by saescapa** [comment]
Update: Still contacting potential speakers and waiting for responses.

**Comment by selynna** [comment]
I'm reassigning this issue to myself because @saescapa has the ACT this weekend, and ideally we'd like to clear this issue out asap

**Comment by zachlatta** [comment]
Found and confirmed someone :-).
